name: bhpwave-env
channels:
  - defaults
  - conda-forge
dependencies:
  - gcc_linux-64
  - gxx_linux-64
  - gsl
  - numpy
  - Cython
  - pip
  - python=3.7
  - sphinx-book-theme
  - nbsphinx
  - ipykernel
  - myst-nb